# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/Atlantic18/DoctrineExtensions/tree/master/doc/
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        # default: ~
        default:
            tree: true
            timestampable: true # not needed: listeners are not enabled by default
            blameable: true
        # other:
        #     timestampable: true