twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        menu: '@App\Service\Services'
        stat: '@App\Service\Statistique'
when@test:
    twig:
        strict_variables: true
